# Generated by Django 3.1.2 on 2021-12-11 07:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_pattern_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='お問い合わせ日時')),
                ('subject', models.CharField(max_length=100, verbose_name='お問い合わせ件名')),
                ('content', models.CharField(max_length=1000, verbose_name='お問い合わせ内容')),
            ],
        ),
        migrations.AddField(
            model_name='pattern',
            name='dt',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='投稿日時'),
        ),
    ]
