# Generated by Django 3.1.2 on 2021-12-14 05:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20211211_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='pattern',
            name='size',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='糸の太さ'),
        ),
        migrations.CreateModel(
            name='PatternRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='#000000', max_length=7, validators=[django.core.validators.RegexValidator(regex='^#(?:[0-9a-fA-F]{6})$')], verbose_name='色')),
                ('number', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='本数')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.pattern', verbose_name='対象の模様')),
            ],
        ),
    ]
