# Generated by Django 3.2.10 on 2021-12-18 06:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20211214_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='patternrecipe',
            name='dt',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='投稿日時'),
        ),
    ]
